### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mdosch** [caarlos0/sshmarshal#2]
Dear maintainer,

I am planning to create a package for Debian but this missing license information.
Can you please clarify the license.

**Comment by caarlos0** [comment]
as stated in the readme, the code is copied from [x/crypto][crypto] and [this patch][patch] so we can more easily marshal SSH private keys.

[patch]: https://go-review.googlesource.com/c/crypto/+/218620/
[crypto]: https://github.com/golang/crypto

**Comment by caarlos0** [comment]
Their license is: https://github.com/golang/crypto/blob/master/LICENSE

This is hopefully a temporary package just until that patch gets merged.

**Comment by mdosch** [comment]
Thank you for clarifying. :)
